apiVersion: v1
kind: Service
metadata:
  name: cicd-node-application
spec:
  type: NodePort
  selector:
    app: cicd-node-application
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-node-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-node-application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-app-cicd
    spec:
      containers:
      - name: node-app-cicd
        image: jenkinsproject/cicd-node-application
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      restartPolicy: Always
status: {}

